#!/bin/bash
# #!명령은 이화일을 실행시킬 shell이 존재하는 path을 지정

######################################################################
# [warning] should be modified here
######################################################################
proFILEdir=$(readlink -f $(dirname $BASH_SOURCE))
if [ "${proFILEdir##*/}" != ".proFILEs" ] || [ -z "${proFILEdir}" ]; then
  echo "Your project is located here: [$proFILEdir]"
  echo 'Yor project must be located ~/.proFILEs'
  read -p 'usage: git clone git@github.com:av930/proFILEs.git ~/.proFILEs'
  exit
fi

SRC=${proFILEdir}
DST=$HOME


######################################################################
# pop up message
######################################################################
function winpop() {
    echo $USERNAME SUCCESS! copy from $1  to $2;
    #$1은 첫번째 인자, $2하면 두번째인자...로 무한대 지원가능 
    #echo 대신 net send 이용가능
    return 0
}


######################################################################
# make copy
######################################################################
function copy_tools() {
    proFILEdir=$SRC
    proFILEdirOS='unknown'

    if [ $(expr match "$OSTYPE" 'cygwin') -ne 0 ]
    then proFILEdirOS=${proFILEdir}/cygwin
    else proFILEdirOS=${proFILEdir}/linux
    fi

    printf "======================================================================\n"
    printf " COPY from ${proFILEdir} to $HOME dir\n"
    set -x
    pushd ${proFILEdir}

    cp ${1} default.config $HOME/profile.config

    cp ${1}R .byobu/ $HOME/
    ln -fs  ${proFILEdir}/.inputrc        $HOME/.inputrc
    ln -fs  ${proFILEdir}/.screenrc       $HOME/.screenrc
    ln -fs  ${proFILEdir}/.splintrc       $HOME/.splintrc
    ln -fs  ${proFILEdir}/.astylerc       $HOME/.astylerc
    ln -fs  ${proFILEdir}/.indent.pro     $HOME/.indent.pro
    ln -fs  ${proFILEdir}/.gitignore      $HOME/.gitignore
    ln -fs  ${proFILEdirOS}/.gitconfig    $HOME/.gitconfig


    ln -fs  ${proFILEdir}/.bash_aliases   $HOME/.bash_aliases
    if [ -f "$HOME/.profile" ]; then mv "$HOME/.profile" "$HOME/.profile_backup";  fi
    ln -fs  ${proFILEdir}/.profile      $HOME/.profile

    popd
    set +x

    #Recursive - sub dircetory ,
    #update - only udated file,
    #verbose - what is being done
    #force, - remove and copy

    winpop $2 $3
    return 0
}


######################################################################
# make remove
######################################################################
function remove_tools() {

    rm -f $HOME/.inputrc      \
          $HOME/.screenrc     \
          $HOME/.splintrc     \
          $HOME/.astylerc     \
          $HOME/.indent.pro   \
          $HOME/.gitignore    \
          $HOME/.gitconfig    \
          $HOME/.bash_aliases \
          $HOME/.profile      \

    return 0
}


######################################################################
# main function
######################################################################
printf "CONFIRM : WILL UPDATE & COPY from $SRC $DST"
printf "\n[c)opy/ u)pdate b)ackup r)remove n)oting]: "
read confirm
if [ "$confirm" = "c" ]; then
    copy_tools -ivf
elif [ "$confirm" = "u" ]; then
    copy_tools -iuvf
elif [ "$confirm" = "b" ]; then
    #backup을 만듦 
    copy_tools -ibuvf 
elif [ "$confirm" = "r" ]; then
    remove_tools
else 
    print "nothing happend, canceled all job"
fi

######################################################################
# post check
######################################################################
if [ ! -x $(which screen) ]
then echo "you need to run: sudo apt-get install screen"
fi
exit 0
